# Generated by Django 5.2.4 on 2025-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arxivdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surename', models.CharField(max_length=15)),
                ('faculty', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=6)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
